//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> Category_Id { get; set; }
    
        public virtual category category { get; set; }
    }
}
